<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="PokeApiNet" Version="4.1.0" />
      <PackageReference Include="Serilog" Version="4.4.0" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="StackExchange.Redis">
        <HintPath>..\..\..\.nuget\packages\stackexchange.redis\3.1.31\lib\net10.0\StackExchange.Redis.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Poke.Redis\Poke.Redis.csproj" />
    </ItemGroup>

</Project>
